# -*- coding: utf-8 -*-
"""Command .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pcirmSJW8wNfDen_ZFpv0DY5iq4xVSf
"""

#!pip install ipywidgets  Ejecuta solo si no lo tienes instalado

from ipywidgets import Button, VBox, Output
from IPython.display import display

# Clase base
class Comando:
    def ejecutar(self):
        pass

# Comandos concretos
class EncenderLuz(Comando):
    def ejecutar(self):
        return "💡 La luz ha sido encendida."

class ApagarLuz(Comando):
    def ejecutar(self):
        return "💡 La luz ha sido apagada."

# Invocador: Botón interactivo
class BotonComando:
    def __init__(self, nombre, comando):
        self.boton = Button(description=nombre)
        self.comando = comando
        self.salida = Output()

        self.boton.on_click(self._accion)

    def _accion(self, b):
        with self.salida:
            print(self.comando.ejecutar())

    def mostrar(self):
        display(VBox([self.boton, self.salida]))

# Uso
boton_on = BotonComando("Encender", EncenderLuz())
boton_off = BotonComando("Apagar", ApagarLuz())

boton_on.mostrar()
boton_off.mostrar()