# -*- coding: utf-8 -*-
"""Observer .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pcirmSJW8wNfDen_ZFpv0DY5iq4xVSf
"""

class Usuario:
    def __init__(self):
        self._estado = "inactivo"
        self._observadores = []

    def registrar_observador(self, observador):
        self._observadores.append(observador)

    def cambiar_estado(self, nuevo_estado):
        self._estado = nuevo_estado
        print(f"⚙️ Estado del usuario cambiado a: {self._estado}")
        self.notificar()

    def notificar(self):
        for observador in self._observadores:
            observador.actualizar(self._estado)

class PanelAdmin:
    def actualizar(self, estado):
        print(f"📢 Panel recibe notificación: Usuario está {estado}")

usuario = Usuario()
panel = PanelAdmin()

usuario.registrar_observador(panel)

# Cambiar manualmente el estado
usuario.cambiar_estado("activo")   # Cambia a activo
usuario.cambiar_estado("inactivo") # Cambia a inactivo