# -*- coding: utf-8 -*-
"""Strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pcirmSJW8wNfDen_ZFpv0DY5iq4xVSf
"""

class EstrategiaUsuario:
    def mostrar_mensaje(self, nombre):
        raise NotImplementedError()

class Admin(EstrategiaUsuario):
    def mostrar_mensaje(self, nombre):
        return f"👑 Bienvenido administrador {nombre}, tienes control total del sistema."

class Cliente(EstrategiaUsuario):
    def mostrar_mensaje(self, nombre):
        return f"🛒 Hola {nombre}, gracias por usar nuestra aplicación como cliente."

class Invitado(EstrategiaUsuario):
    def mostrar_mensaje(self, nombre):
        return f"👤 Hola {nombre}, estás accediendo como invitado. Algunas funciones están limitadas."

class Usuario:
    def __init__(self, nombre, tipo):
        self.nombre = nombre
        self._estrategia = self._seleccionar_estrategia(tipo)

    def _seleccionar_estrategia(self, tipo):
        tipo = tipo.lower()
        if tipo == "admin":
            return Admin()
        elif tipo == "cliente":
            return Cliente()
        else:
            return Invitado()

    def mostrar_mensaje_personalizado(self):
        print(self._estrategia.mostrar_mensaje(self.nombre))

# Uso en Colab
nombre = input("Ingrese su nombre: ")
tipo_usuario = input("Ingrese su tipo de usuario (admin/cliente/invitado): ")

persona = Usuario(nombre, tipo_usuario)
persona.mostrar_mensaje_personalizado()